### ISSUE TITLE
Null from craft.geomate.redirectInformation()

### ISSUE THREAD

**Issue by matthewbacon** [vaersaagod/geomate#30]
Having installed Geomate via composer I can access all craft.geomate.country, craft.geomate.countryCode and craft.geomate.city within my templates. HOWEVER I have been unsuccessful in retrieving anything except NULL from redirect information.

geomete.php (in config folder) looks like...

```
<?php
return [
    'autoRedirectEnabled' => true,
    'redirectIgnoreAdmins' => false,
    'redirectMap' => [
        'eu' => [
            'continent' => 'eu',
            'isInEuropeanUnion' => true
        ],
        'europe' => [
            'continent' => 'eu',
        ],
        'us' => [
            'country' => 'us'
        ],    
        'global' => '*' 
    ]
];
```

While in my template files I am using...

```
{% set redirectInfo = craft.geomate.redirectInformation() %}
{{ dump(redirectInfo) }}
```

Sorry, what am I doing wrong?

**Comment by matthewbacon** [comment]
I've tested via Incognito browsers as well in case it was because I was logged in as Admin. Same results.

**Comment by aelvan** [comment]
I see that you have `'autoRedirectEnabled' => true,`, maybe that's why. If you're already on the site that the user is meant to end up on, ie you've been redirected there, `craft.geomate.redirectInformation()` will always be `null`. That function is meant to be used in cases where you don't have `autoRedirectEnabled` enabled, and instead want to figure out if the user should be redirected, and either do it manually, or present the user with the option.
