### ISSUE TITLE
Errors produced when forceIp set in geomete.php

### ISSUE THREAD

**Issue by alliancemediacom** [vaersaagod/geomate#4]
I've installed geomete by following the instructions provided. As I'm working locally I've set my forceIp to my local IP address as follows:

`return [
    'forceIp' => 'IP-ADDRESS-HERE'
];`

When I add the following to my twig template `{{ craft.geomate.country }}` and run it I receive the following error:

> PHP Recoverable Error – yii\base\ErrorException
> Object of class GeoIp2\Model\Country could not be converted to string

Any advise on how to sort this would be greatly appreciated.

**Comment by aelvan** [comment]
The error is just due to you trying to output the value that `craft.geomate.country` outputs, directly. As the error message states, this is a complete object of type `GeoIp2\Model\Country`, which you need to drill into to get exactly what you want. To get an idea of what information is vailable, you can use `dump()` if you're in devMode, ie `{{ dump(craft.geomate.country) }}`.

Some examples:

```
{% set countryData = craft.geomate.country() %}
{{ countryData.country.name }}<br>
{{ countryData.country.isoCode }}<br>
{{ countryData.country. isInEuropeanUnion }}<br>
{{ countryData.continent.name }}<br>
```

You can also learn more from looking at the [models](https://github.com/maxmind/GeoIP2-php/tree/master/src/Model) and [records](https://github.com/maxmind/GeoIP2-php/tree/master/src/Record) of the underlying [Maxmind DB library source](https://github.com/maxmind/GeoIP2-php/).
