### ISSUE TITLE
Error "Class 'Locale' not found" when using redirectMapSimpleModeKey => language

### ISSUE THREAD

**Issue by MetaDevelopment** [vaersaagod/geomate#5]
Great plugin, thank you very much! However, I think I'm doing something wrong: I set up the plugin with the config as follows:

        // Redirect automatically
        'autoRedirectEnabled' => true,

        'redirectMap' => [
            'nl' => 'nl',
            'fr' => 'fr',
            'en' => '*'
        ],

        'redirectIgnoreAdmins' => false,
        'forceIp' => _my-ip-address_,

And this works, I get redirected. However, when I add "'redirectMapSimpleModeKey' => 'language'," to the config, any page I visit gives the following error:

Class 'Locale' not found

The same happens when I use "craft.geomate.getLanguages()" in my templates (with and without setting the redirectMapSimpleModeKey option to true).

**Comment by aelvan** [comment]
Can you post more of the stacktrace for that error, so that I know where it fails?

**Comment by MetaDevelopment** [comment]
Hi @aelvan , have you been able to locate the error based on the stacktrace?

**Comment by pl-mnm** [comment]
Hi, I'm having the exact same issue, and the stack trace looks the same. If it matters, I'm using multiple sites, and one has two locales: The main site's language is `en-GB`,  the other site is set in `en-GB` and `fr`. Has anyone figured out the source of the problem?

**Comment by aelvan** [comment]
I think this is caused by not having the intl php extension. The class referred to is the [Locale class](https://www.php.net/manual/en/class.locale.php) in PHP. The `zonuexe/http-accept-language` package has a requirement for ext-intl, and I kinda assumed that that would be picked up by craft/geomate, but maybe I have to add it explicitly to the composer.json file. 

Can you guys check if intl is missing from php (you can use the system report tool in Craft, it'll list it under requirements), and confirm if adding it fixes the issue?

**Comment by pl-mnm** [comment]
Adding the intl extension worked for me, thanks for your help and a stellar jobs on all your plugins!
