### ISSUE TITLE
Error when using 'redirectMapSimpleModeKey' => 'language',

### ISSUE THREAD

**Issue by sandrodunkel** [vaersaagod/geomate#51]
Config:
```
<?php

return [
    '*' => [
        'autoRedirectEnabled' => true,

        'redirectMapSimpleModeKey' => 'language',
        
        'redirectMap' => [
            'siteHandleDe' => [
                'language' => 'de',
            ],
            'siteHandleFr' => [
                'language' => 'fr',
            ],
        ]
    ],
];
```

Using this config, I get the following error:
```
vaersaagod\geomate\services\RedirectService::getSiteFromInfoAndMap(): Argument #1 ($countryInfo) must be of type GeoIp2\Model\City|GeoIp2\Model\Country, null given, called in /Users/username/Web Projects/blp/vendor/vaersaagod/geomate/src/services/RedirectService.php on line 99
```

Since my `redirectMapSimpleModeKey` is set to `language` I do not get why the error calls for a country. What am I missing?

Craft CMS 4.2.7
GeoMate 2.0.0
PHP 8.0.8

**Comment by mmikkel** [comment]
Hi @sandrodunkel,

I assume your GeoIP2 databases are missing? To confirm, visit the GeoMate utility under Utilities -> GeoMate in the Craft CP.

**To make the exception go away, download the GeoIP2 databases as per [the docs](https://github.com/vaersaagod/geomate#downloading-the-geolocation-database).**

To be clear, there _is_ a bug in GeoMate here – the fact that an exception is thrown, instead of GeoMate logging the error and failing silently, like it's supposed to. I'll get a fix out for that shortly.

> Since my redirectMapSimpleModeKey is set to language I do not get why the error calls for a country. 

It doesn't. The issue is that GeoMate was never designed to any kind of redirect (including based on browser language) without there being a database for IP lookups present. So essentially, all the redirect logic is dependent on that database being present, whether it's actually needed or not.

That said, I do think your assumption is legit. IP lookups are not relevant when doing language-based redirects, so ideally redirects based on browser language should always work regardless of there being a IP lookup database present or not. I'll look into making that change in a future release!

Also – not that it technically makes a difference in this case, but when you've set the `redirectMapSimpleModeKey` setting to `'language'`, also specifying 'language' in the `redirectMap` as well is redundant. So in your case, your config could be simplified like this:

```php
<?php

return [
    '*' => [
        'autoRedirectEnabled' => true,

        'redirectMapSimpleModeKey' => 'language',
        
        'redirectMap' => [
            'siteHandleDe' => 'de',
            'siteHandleFr' => 'fr',
        ]
    ],
];
```

**Comment by mmikkel** [comment]
This should be resolved in [GeoMate v. 2.1.0](https://github.com/vaersaagod/geomate/releases/tag/2.1.0).
